# --------------------------- #
#   Anypoint Platform Config  #
# --------------------------- #

password-manager-api:
  anypoint:
    name: "Password Manager API v1"
    base-path: "/v1"
    listener:
      config-ref: "password-manager-api-http"
    organization-id: "98917c73-8c76-40c5-a499-a7959f76eae1"

# --------------------------- #
#     HTTP/HTTPS Settings     #
# --------------------------- #

config:
  http:
    port: "8091"
  https:
    port: "8082"
    
oauth:
  grant-types:
    client-credentials: "CLIENT_CREDENTIALS"
    
files:
  encrypted-files:
    path: "database"
    