# --------------------------- #
#   Anypoint Platform Config  #
# --------------------------- #

password-manager-api:
  anypoint:
    name: "Password Manager API v1"
    base-path: "/v1"
    listener:
      config-ref: "password-manager-api-http"
    organization-id: "7994c6af-afcc-42f8-8fcd-720038995f2c"

# --------------------------- #
#     HTTP/HTTPS Settings     #
# --------------------------- #

config:
  http:
    port: "8091"
  https:
    port: "8082"
    
oauth:
  grant-types:
    client-credentials: "CLIENT_CREDENTIALS"
    