# --------------------------- #
#   Anypoint Platform Config  #
# --------------------------- #

password-manager-api:
  anypoint:
    name: "Password Manager API v1"
    base-path: "/v1"
    listener:
      config-ref: "password-manager-api-http"
    organization-id: "57cbb486-f7ad-48ae-96ef-0c53d8886821"

# --------------------------- #
#     HTTP/HTTPS Settings     #
# --------------------------- #

config:
  http:
    port: "8091"
  https:
    port: "8082"
    
oauth:
  grant-types:
    client-credentials: "CLIENT_CREDENTIALS"
    
files:
  encrypted-files:
    path: "database"
    