# --------------------------- #
#   Anypoint Platform Config  #
# --------------------------- #

password-manager-api:
  anypoint:
    auto-discovery-id: "18646718"
    # At the moment conenctedApp credentials are not used
    connected-app:
      client-id: "3c508a3aa30e4df8ba9d8dd06f714da4"
      client-secret: "![VH/+sY5xLUedYPZRQcNGQcC6VIpWQKVQcHN9rm0TTjl4vQj0fueX8oIpVFirokp/vC1z/w7jIsh1izWpkIc3iQ==]"
    username: "deacudavidism3"
    password: "![ww1DGObDFOvfijKhASNB0CqQElLmlthBTlpttsFuISYpIly5Gj2Bpu+9yWUKKRAj]"

# --------------------------- #
#     KeyStore Config         #
# --------------------------- #

key-store:
  path: keystore.jks
  key-password: "![+WOzAb9zRcx+cZ3C2kXbfpcgJOSqa3Bcz6K9GOKEttieO6rKKsupin7vlGWEt6G3]"
  password: "![4spEpdLXowXwczJqbPSdddGK8YBcQA6mFQhPRhZLN6BSGD5WyqcAhpjfX1r3eq+m]"

aws-s3:
  iam:
    access-key: "![lo5VACyw2eGJ8eu16SNt0bdSKiJMTBoVFRBk7MwU30woS8mCIQz+uwkL0oLwlDRz]"
    access-secret-key: "![nltYaP/V2cF0p8khjzkmvf9bpTOyXATIvsBsCLG0SH9sM+6aQ+V/GWlQaAwW5HKqV3fDxcawClbNjvrqTK2VEg==]"
